#! /bin/sh

bspc config border_width        4
bspc config window_gap         12
bspc config top_padding        10

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     false
bspc config focus_by_distance   true
bspc config pointer_follows_monitor true
#bspc config focus_follows_pointer true

bspc monitor DVI-I-1 -d I II III IV V
bspc monitor DVI-D-0 -d VI VII VIII IX X

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

pkill panel
panel &
konsole &
xscreensaver &
nitrogen --restore &
sleep 1
stalonetray --geometry 4x1+1720-1060 -bg '#34322e' &
